[package]
org = "danesh"
name = "mock_with_inmemory"
version = "0.1.0"
distribution = "2201.8.2"

[build-options]
observabilityIncluded = true

[persist]
datastore = "inmemory"
module = "mock_with_inmemory"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.2.0"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.2.0"
